- id: doi:10.1109/TCAD.2023.3285410
  type: paper
  description: description here
  date: 2023-6-12
  image: images/brain.png
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/UA-RCL/RANC
    - type: website
      link: projects/ranc
  tags:
    - can add tags here
  repo: UA-RCL/RANC

- id: doi:10.1145/3529257
  type: paper
  description: description here
  date: 2023-1-24
  image: images/soc.png
  buttons:
    - type: source
      text: Source Code
      link: https://github.com/UA-RCL/CEDR
    - type: website
      link: projects/cedr
  tags:
    - can add tags here
  repo: UA-RCL/CEDR